// Project Brain — public API for the daemon. Black wires server.js to THIS.
//
//   const brain = require("./brain");
//   // POST /project/scan {project}  →  const b = brain.buildBrain({id,name,dir}); res.end(JSON.stringify(b.summary))
//   // GET  /project/brain?project=  →  res.end(JSON.stringify(brain.getBrain(projectId) || {error:"not scanned"}))
//
// buildBrain is synchronous + bounded (see engine caps). No daemon globals
// required; pass the project {id,name,dir}. Persists a cache + auto-inits the
// project's .claude/.codex brain files. Returns { summary, brain }.
"use strict";
const fs = require("fs");
const path = require("path");
const { scan, buildGraph, buildMapping } = require("./engine");

const CACHE_DIR = path.join(__dirname, "..", "brain-cache");
function cacheFile(projectId) { return path.join(CACHE_DIR, String(projectId).replace(/[^a-zA-Z0-9_-]/g, "_") + ".json"); }

function buildBrain(project, opts = {}) {
  if (!project || !project.dir) throw new Error("project {id,name,dir} required");
  const dir = project.dir;
  if (!fs.existsSync(dir)) throw new Error("project dir not found: " + dir);
  const startedTs = opts.now || 0; // caller stamps real time; engine stays deterministic

  const scanRes = scan(dir, opts);
  const graph = buildGraph(scanRes);
  const mapping = buildMapping(scanRes, graph);

  const totalLoc = scanRes.files.reduce((s, f) => s + (f.loc || 0), 0);
  const brain = {
    projectId: project.id || null,
    projectName: project.name || path.basename(dir),
    root: dir,
    generatedTs: startedTs,
    stats: {
      files: scanRes.count,
      loc: totalLoc,
      edges: graph.edges.length,
      externals: Object.keys(graph.externals).length,
      truncated: scanRes.truncated,
    },
    languages: scanRes.langs,
    modules: mapping.modules,
    entryPoints: mapping.entryPoints,
    hotspots: mapping.hotspots,
    topExternals: mapping.topExternals,
    graph,                 // {nodes, edges, externals}
  };

  // persist cache (graph can be large — keep it; it's the whole point)
  try { fs.mkdirSync(CACHE_DIR, { recursive: true }); fs.writeFileSync(cacheFile(project.id || project.name), JSON.stringify(brain)); } catch {}

  // auto-init the agents' context files in the project
  const initialized = autoInit(dir, brain);

  // compact summary for the wire / UI (omit the heavy full graph)
  const summary = {
    projectId: brain.projectId, projectName: brain.projectName, root: dir,
    stats: brain.stats, languages: brain.languages,
    modules: brain.modules.slice(0, 12), entryPoints: brain.entryPoints,
    hotspots: brain.hotspots.slice(0, 10), topExternals: brain.topExternals.slice(0, 12),
    initialized, generatedTs: startedTs,
  };
  return { summary, brain };
}

function getBrain(projectId, full = false) {
  try {
    const b = JSON.parse(fs.readFileSync(cacheFile(projectId), "utf8"));
    if (full) return b;
    const { graph, ...rest } = b;
    return { ...rest, modules: rest.modules.slice(0, 12) };
  } catch { return null; }
}

// ---- auto-init .claude / .codex --------------------------------------------
// Writes a dedicated PROJECT_BRAIN.md into the project's .claude/ and .codex/
// so any Claude Code / Codex session opened there starts with the map.
// NEVER overwrites the user's own files — only our PROJECT_BRAIN.md.
function autoInit(dir, brain) {
  const md = renderMd(brain);
  const done = [];
  for (const sub of [".claude", ".codex"]) {
    try {
      const d = path.join(dir, sub);
      fs.mkdirSync(d, { recursive: true });
      fs.writeFileSync(path.join(d, "PROJECT_BRAIN.md"), md);
      done.push(sub + "/PROJECT_BRAIN.md");
    } catch {}
  }
  return done;
}

function renderMd(b) {
  const langs = Object.entries(b.languages).sort((a, c) => c[1] - a[1])
    .map(([e, n]) => `${e} ×${n}`).join(", ");
  const mods = b.modules.slice(0, 10).map((m) => `- \`${m.name}/\` — ${m.files} files, ${m.loc} loc`).join("\n");
  const entries = b.entryPoints.slice(0, 10).map((e) => `- \`${e}\``).join("\n") || "- (none detected)";
  const hot = b.hotspots.slice(0, 8).map((h) => `- \`${h.rel}\` (imported by ${h.importedBy})`).join("\n") || "- (none)";
  const ext = b.topExternals.slice(0, 12).map((e) => `${e.pkg} (${e.uses})`).join(", ") || "(none)";
  return `# PROJECT BRAIN — ${b.projectName}
<!-- auto-generated by BagIdea Office Project Brain. Do not edit by hand; re-run /project/scan. -->

**Root:** \`${b.root}\`
**Size:** ${b.stats.files} source files · ${b.stats.loc} loc · ${b.stats.edges} import edges${b.stats.truncated ? " · ⚠ truncated (capped)" : ""}
**Languages:** ${langs}

## Modules (top-level)
${mods}

## Entry points
${entries}

## Core files (most imported)
${hot}

## Key external deps
${ext}
`;
}

module.exports = { buildBrain, getBrain, cacheFile, CACHE_DIR };
